import { useState } from 'react';
import { useData } from '../lib/data-context';
import { updateProfile } from '../lib/db';
import { CatPhotographer } from './Mascot';

function looksAutoGenerated(nick) {
  if (!nick) return true;
  if (/^익명[_-]?[a-z0-9]{2,8}$/i.test(nick)) return true;
  if (/^user[_-]?[a-z0-9]{2,8}$/i.test(nick)) return true;
  if (/^visitor[_-]?[a-z0-9]{2,8}$/i.test(nick)) return true;
  return false;
}

export default function OnboardingModal() {
  const { userId, getProfile, refresh } = useData();
  const profile = getProfile(userId);
  const needsOnboarding = profile && looksAutoGenerated(profile.nickname);
  const [nickname, setNickname] = useState('');
  const [bio, setBio] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);

  if (!needsOnboarding) return null;

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (!nickname.trim()) return;
    setBusy(true);
    setError(null);
    try {
      await updateProfile(userId, {
        nickname: nickname.trim(),
        bio: bio.trim() || null,
      });
      await refresh();
    } catch (err) {
      if (err.code === '23505') setError('이미 쓰는 닉네임이에요. 다른 걸로.');
      else setError(err.message || '저장 실패');
      setBusy(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 p-4 sm:items-center">
      <div className="w-full max-w-[380px] rounded-[20px] bg-[var(--surface)] p-5 shadow-xl">
        <div className="mb-4 flex items-center gap-3">
          <div className="text-[var(--ink)]">
            <CatPhotographer size={48} />
          </div>
          <div>
            <p className="text-[10px] font-semibold tracking-[0.16em] text-[var(--text-muted)]">시선집</p>
            <h2 className="mt-0.5 text-[18px] font-extrabold tracking-[-0.06em]">
              어떻게 불러드릴까요?
            </h2>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-2">
          <input
            value={nickname}
            onChange={(event) => setNickname(event.target.value)}
            placeholder="닉네임"
            required
            maxLength={20}
            autoFocus
            className="w-full rounded-[12px] border border-[var(--border)] bg-[var(--bg)] px-3.5 py-2.5 text-[14px] outline-none focus:border-[var(--ink)]"
          />
          <textarea
            value={bio}
            onChange={(event) => setBio(event.target.value)}
            placeholder="짧은 소개 (선택)"
            maxLength={80}
            className="min-h-[60px] w-full resize-none rounded-[12px] border border-[var(--border)] bg-[var(--bg)] px-3.5 py-2.5 text-[13px] outline-none focus:border-[var(--ink)]"
          />
          {error && <p className="text-[11px] text-red-600">{error}</p>}
          <button
            type="submit"
            disabled={busy || !nickname.trim()}
            className="w-full rounded-full bg-[var(--ink)] py-3 text-[14px] font-semibold text-white disabled:opacity-50"
          >
            {busy ? '시작 중…' : '시작'}
          </button>
        </form>
      </div>
    </div>
  );
}
