import { useState } from 'react';
import { useData } from '../lib/data-context';
import { updateProfile } from '../lib/db';

function looksAutoGenerated(nick) {
  if (!nick) return true;
  if (/^익명[_-]?[a-z0-9]{2,8}$/i.test(nick)) return true;
  if (/^user[_-]?[a-z0-9]{2,8}$/i.test(nick)) return true;
  if (/^visitor[_-]?[a-z0-9]{2,8}$/i.test(nick)) return true;
  return false;
}

export default function OnboardingModal() {
  const { userId, getProfile, refresh } = useData();
  const profile = getProfile(userId);
  const needsOnboarding = profile && looksAutoGenerated(profile.nickname);
  const [nickname, setNickname] = useState('');
  const [bio, setBio] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);

  if (!needsOnboarding) return null;

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (!nickname.trim()) return;
    setBusy(true);
    setError(null);
    try {
      await updateProfile(userId, {
        nickname: nickname.trim(),
        bio: bio.trim() || null,
      });
      await refresh();
    } catch (err) {
      if (err.code === '23505') setError('이미 쓰는 닉네임이에요. 다른 걸로.');
      else setError(err.message || '저장 실패');
      setBusy(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 p-4 sm:items-center">
      <div className="mx-auto w-full max-w-[400px] rounded-[24px] bg-[var(--surface)] p-6 shadow-xl">
        <p className="text-[11px] font-semibold tracking-[0.16em] text-[var(--text-muted)]">시선집에 오신 걸 환영해요</p>
        <h2 className="mt-1 text-[26px] font-extrabold leading-tight tracking-[-0.07em]">
          어떻게 불러드릴까요?
        </h2>
        <p className="mt-3 text-sm leading-6 text-[var(--text-body)]">
          닉네임과 짧은 소개를 적어주세요. 다른 사람의 개인전에 보이는 이름이에요.
        </p>

        <form onSubmit={handleSubmit} className="mt-5 space-y-3">
          <input
            value={nickname}
            onChange={(event) => setNickname(event.target.value)}
            placeholder="닉네임 (필수)"
            required
            maxLength={20}
            autoFocus
            className="w-full rounded-[16px] border border-[var(--border)] bg-white px-4 py-3 text-sm outline-none focus:border-[var(--ink)]"
          />
          <textarea
            value={bio}
            onChange={(event) => setBio(event.target.value)}
            placeholder="짧은 소개 (선택) — 예: 모서리와 빛을 모읍니다"
            maxLength={80}
            className="min-h-20 w-full resize-none rounded-[16px] border border-[var(--border)] bg-white px-4 py-3 text-sm outline-none focus:border-[var(--ink)]"
          />
          {error && <p className="rounded-[12px] bg-red-50 p-2 text-xs text-red-700">{error}</p>}
          <button
            type="submit"
            disabled={busy || !nickname.trim()}
            className="w-full rounded-full bg-[var(--ink)] px-5 py-4 text-sm font-semibold text-white disabled:opacity-50"
          >
            {busy ? '시작 중…' : '시작하기'}
          </button>
        </form>
      </div>
    </div>
  );
}
